### ISSUE TITLE
command failed: prv-stat

### ISSUE THREAD

**Issue by MarvinT** [flatironinstitute/mountainsort#26]
Hey, I'm running into the following error.

```
psych-airflow@txori:/home/AD/mthielk$ mlp-run /mnt/cube/tsainbur/Projects/github_repos/mountainsort/pipelines/mountainsort3.mlp sort --raw=/mnt/cube/mthielk/analysis/B1218/mtnsort/Pen01_Lft_AP2500_ML160__Site02_Z2337__B1218_cat_P01_S02_1/Pen01_Lft_AP2500_ML160__Site02_Z2337__B1218_cat_P01_S02_1.mda --firings_out=/mnt/cube/mthielk/analysis/B1218/mtnsort/Pen01_Lft_AP2500_ML160__Site02_Z2337__B1218_cat_P01_S02_1/firings.mda --_params=/mnt/cube/mthielk/analysis/B1218/mtnsort/Pen01_Lft_AP2500_ML160__Site02_Z2337__B1218_cat_P01_S02_1/params.json --curate=false
Using data directory: /mnt/cube/tmp/mountainlab/prvbucket
Computing checksum for file: /mnt/cube/mthielk/analysis/B1218/mtnsort/Pen01_Lft_AP2500_ML160__Site02_Z2337__B1218_cat_P01_S02_1/Pen01_Lft_AP2500_ML160__Site02_Z2337__B1218_cat_P01_S02_1.mda
child_process.js:507
    throw err;
    ^

Error: Command failed: prv-stat /mnt/cube/mthielk/analysis/B1218/mtnsort/Pen01_Lft_AP2500_ML160__Site02_Z2337__B1218_cat_P01_S02_1/Pen01_Lft_AP2500_ML160__Site02_Z2337__B1218_cat_P01_S02_1.mda

    at checkExecSyncError (child_process.js:464:13)
    at Object.execSync (child_process.js:504:13)
    at prv_stat_sync (/usr/share/mlpipeline/utils/mlp/mlp-run:242:35)
    at step2 (/usr/share/mlpipeline/utils/mlp/mlp-run:155:12)
    at /usr/share/mlpipeline/utils/mlp/mlp-run:69:4
    at /usr/share/mlpipeline/web/mlpipeline/kuleleclient.js:322:4
    at /usr/share/mlpipeline/processing_server/larinet/larinetserver.js:260:4
    at /usr/share/mlpipeline/processing_server/larinet/larinetserver.js:544:5
    at ChildProcess.<anonymous> (/usr/share/mlpipeline/processing_server/larinet/larinetserver.js:713:3)
    at emitTwo (events.js:87:13)
```

I've generated the mda file using this python script that I wrote to convert raw.kwd files to your mda format:
https://github.com/gentnerlab/klusta-pipeline/blob/master/klusta_pipeline/kwd2mda.py

I haven't wrapped my head around the whole mountainlab pipeline yet.
Any pointers on where to look?

**Comment by magland** [comment]
I wonder if "prv-stat" is installed properly. How did you install mountainlab? Using ppa?

**Comment by MarvinT** [comment]
yup, using ppa.

I think it has something to do with permissions.

I can run it with sudo -HE

I had it running without sudo a couple of days ago and I'm not sure what changed. We haven't restarted the server or anything.

What files and paths are being used for checksumming?

**Comment by MarvinT** [comment]
actually 
``` 
prv-stat /mnt/cube/mthielk/analysis/B1218/mtnsort/Pen01_Lft_AP2500_ML160__Site02_Z2337__B1218_cat_P01_S02_1/Pen01_Lft_AP2500_ML160__Site02_Z2337__B1218_cat_P01_S02_1.mda 
```
runs fine without sudo, although it doesn't output anything

**Comment by MarvinT** [comment]
actually, actually,

```
prv-stat /mnt/cube/mthielk/analysis/B1218/mtnsort/Pen01_Lft_AP2500_ML160__Site02_Z2337__B1218_cat_P01_S02_1/Pen01_Lft_AP2500_ML160__Site02_Z2337__B1218_cat_P01_S02_1.mda; echo $?
```

returns 255 / -1 so I guess I'll dig into prv-stat next

**Comment by MarvinT** [comment]
alright... for anyone who gets this error... check the pathname for your file :( ... my bad.

P.S. a nicer error message here might be helpful

**Comment by magland** [comment]
Thanks MarvinT!

Yes, a lot of the errors are not helpful... ultimately we will scrub through the software and make helpful messages.
