### ISSUE TITLE
Problem in TextFile::write

### ISSUE THREAD

**Issue by tbenst** [flatironinstitute/mountainsort#31]
I am on ubuntu 16.04 and just followed the instructions at https://mountainsort.readthedocs.io/en/latest/. I get the following error:
```
~/lib$ mp-list-processors
Warning: Problem in TextFile::write. Could not remove file even though it exists "/tmp/mountainlab/expiration_records/590878fec4678f4c9e015e3c5d883fc6014898dd.json"
Warning: Problem in TextFile::write. Could not remove file even though it exists "/tmp/mountainlab/expiration_records/590878fec4678f4c9e015e3c5d883fc6014898dd.json"
Warning: Problem in TextFile -- unable to write file:  "/tmp/mountainlab/expiration_records/590878fec4678f4c9e015e3c5d883fc6014898dd.json"
Warning: Problem in TextFile::write. Could not remove file even though it exists "/tmp/mountainlab/expiration_records/329483bb0aaad2a62b749a1f8f19c7a9322b26fd.json"
Warning: Problem in TextFile::write. Could not remove file even though it exists "/tmp/mountainlab/expiration_records/329483bb0aaad2a62b749a1f8f19c7a9322b26fd.json"
Warning: Problem in TextFile -- unable to write file:  "/tmp/mountainlab/expiration_records/329483bb0aaad2a62b749a1f8f19c7a9322b26fd.json"
Warning: Problem in TextFile::write. Could not remove file even though it exists "/tmp/mountainlab/expiration_records/72a73fdc0a2bdc16398bfb63c4fb5a02b8910c2b.json"
Warning: Problem in TextFile::write. Could not remove file even though it exists "/tmp/mountainlab/expiration_records/72a73fdc0a2bdc16398bfb63c4fb5a02b8910c2b.json"
Warning: Problem in TextFile -- unable to write file:  "/tmp/mountainlab/expiration_records/72a73fdc0a2bdc16398bfb63c4fb5a02b8910c2b.json"
Warning: Problem in TextFile::write. Could not remove file even though it exists "/tmp/mountainlab/expiration_records/98f9e6e711e182a2e9c7e47c8b41b5750f776e16.json"
Warning: Problem in TextFile::write. Could not remove file even though it exists "/tmp/mountainlab/expiration_records/98f9e6e711e182a2e9c7e47c8b41b5750f776e16.json"
Warning: Problem in TextFile -- unable to write file:  "/tmp/mountainlab/expiration_records/98f9e6e711e182a2e9c7e47c8b41b5750f776e16.json"
Warning: Problem in TextFile::write. Could not remove file even though it exists "/tmp/mountainlab/expiration_records/ab654a863e0e4acfccf2ba5a2c9bdbea6dc77326.json"
Warning: Problem in TextFile::write. Could not remove file even though it exists "/tmp/mountainlab/expiration_records/ab654a863e0e4acfccf2ba5a2c9bdbea6dc77326.json"
Warning: Problem in TextFile -- unable to write file:  "/tmp/mountainlab/expiration_records/ab654a863e0e4acfccf2ba5a2c9bdbea6dc77326.json"
Warning: Problem in TextFile::write. Could not remove file even though it exists "/tmp/mountainlab/expiration_records/155d055cb7f596c634f9201cf288ddd286c1deec.json"
Warning: Problem in TextFile::write. Could not remove file even though it exists "/tmp/mountainlab/expiration_records/155d055cb7f596c634f9201cf288ddd286c1deec.json"
Warning: Problem in TextFile -- unable to write file:  "/tmp/mountainlab/expiration_records/155d055cb7f596c634f9201cf288ddd286c1deec.json"
banjoview.cross_correlograms
mountainsortalg.ms3
mountainsortalg.ms3alg
ms3.apply_timestamp_offset
ms3.apply_whitening_matrix
ms3.bandpass_filter
ms3.cluster_metrics
ms3.combine_cluster_metrics
ms3.combine_firing_segments
ms3.combine_firings
ms3.compute_amplitudes
ms3.compute_templates
ms3.compute_whitening_matrix
ms3.concat_event_times
ms3.concat_firings
ms3.concat_timeseries
ms3.confusion_matrix
ms3.create_firings
ms3.create_multiscale_timeseries
ms3.extract_clips
ms3.extract_firings
ms3.isolation_metrics
ms3.link_segments
ms3.load_test
ms3.mask_out_artifacts
ms3.mv_compute_amplitudes
ms3.mv_compute_templates
ms3.mv_discrimhist
ms3.mv_extract_clips
ms3.mv_extract_clips_features
ms3.mv_subfirings
ms3.reorder_labels
ms3.run_metrics_script
ms3.split_firings
ms3.whiten
ms3.whiten_clips
pyms.apply_label_map
pyms.compute_accuracies
pyms.compute_templates
pyms.create_label_map
pyms.extract_clips
pyms.extract_geom
pyms.extract_timeseries
pyms.normalize_channels
pyms.synthesize_drifting_timeseries
pyms.synthesize_random_firings
pyms.synthesize_random_waveforms
pyms.synthesize_timeseries
spikeview.metrics1
spikeview.templates

/opt/mountainsort_examples/examples/example1_mlp$ mlp-run mountainsort3.mlp sort --raw=data/raw.mda --geom=data/geom.csv --firings_out=data/firings.mda --_params=params.json
Using pipeline: mountainsort3.mlp
Using data directory: /tmp/mountainlab/prvbucket
Error getting processor spec: Problem writing req to file
```

I do have Anaconda installed and it is on my path if that helps with debugging. Thanks for your help!

**Comment by magland** [comment]
How much disk space is in your /tmp directory?

**Comment by tbenst** [comment]
Not enough! Thanks. Having a few new issues now:

```
$ mp-list-processors
2018-02-08:10-46-58-899	mproc.processormanager	warning	"Potential problem with executable processor file: /opt/mountainlab/packages/system/rbdownload/rbdownload.mp. Expected json output but got empty string."
2018-02-08:10-46-58-900	mproc.processormanager	warning	"Executable processor file did not return output for spec: /opt/mountainlab/packages/system/rbdownload/rbdownload.mp"
2018-02-08:10-46-59-014	mproc.processormanager	warning	"Potential problem with executable processor file: /opt/mountainlab/packages/system/rbdownload/rbdownload.mp. Expected json output but got empty string."
2018-02-08:10-46-59-014	mproc.processormanager	warning	"Executable processor file did not return output for spec: /opt/mountainlab/packages/system/rbdownload/rbdownload.mp"
banjoview.cross_correlograms
mountainsortalg.ms3
mountainsortalg.ms3alg
ms3.apply_timestamp_offset
ms3.apply_whitening_matrix
ms3.bandpass_filter
ms3.cluster_metrics
ms3.combine_cluster_metrics
ms3.combine_firing_segments
ms3.combine_firings
ms3.compute_amplitudes
ms3.compute_templates
ms3.compute_whitening_matrix
ms3.concat_event_times
ms3.concat_firings
ms3.concat_timeseries
ms3.confusion_matrix
ms3.create_firings
ms3.create_multiscale_timeseries
ms3.extract_clips
ms3.extract_firings
ms3.isolation_metrics
ms3.link_segments
ms3.load_test
ms3.mask_out_artifacts
ms3.mv_compute_amplitudes
ms3.mv_compute_templates
ms3.mv_discrimhist
ms3.mv_extract_clips
ms3.mv_extract_clips_features
ms3.mv_subfirings
ms3.reorder_labels
ms3.run_metrics_script
ms3.split_firings
ms3.whiten
ms3.whiten_clips
pyms.apply_label_map
pyms.compute_accuracies
pyms.compute_templates
pyms.create_label_map
pyms.extract_clips
pyms.extract_geom
pyms.extract_timeseries
pyms.normalize_channels
pyms.synthesize_drifting_timeseries
pyms.synthesize_random_firings
pyms.synthesize_random_waveforms
pyms.synthesize_timeseries
spikeview.metrics1
spikeview.templates
```


Another issue came up when trying to run `mlpipeline synthesize_v1.mlp`  Told me to run:
```
$ mlp-larinet
module.js:472
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/share/mlpipeline/processing_server/larinet/larinet.js:16:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```


And finally:
```
$ mlp-run mountainsort3.mlp sort --raw=data/raw.mda --geom=data/geom.csv --firings_out=data/firings.mda --_params=params.json
Using pipeline: mountainsort3.mlp
Using data directory: /tmp/mountainlab/prvbucket
Computing checksum for file: data/raw.mda
Computing checksum for file: data/geom.csv
----------------------------------------------------------------------------
Queueing job: ms3.bandpass_filter
  INPUTS: timeseries=[object Object]  
  PARAMS: samplerate=30000  freq_min=300  freq_max=6000  freq_wid=1000  quantization_unit=0  subsample_factor=1  
----------------------------------------------------------------------------
  |ms3.bandpass_filter|            2018-02-08:10-54-03-786	mproc.processormanager	warning	"Potential problem with executable processor file: /opt/mountainlab/packages/system/rbdownload/rbdownload.mp. Expected json output but got empty string."
  |ms3.bandpass_filter|            2018-02-08:10-54-03-786	mproc.processormanager	warning	"Executable processor file did not return output for spec: /opt/mountainlab/packages/system/rbdownload/rbdownload.mp"
  |ms3.bandpass_filter|            2018-02-08:10-54-03-924	mproc.processormanager	warning	"Potential problem with executable processor file: /opt/mountainlab/packages/system/rbdownload/rbdownload.mp. Expected json output but got empty string."
  |ms3.bandpass_filter|            2018-02-08:10-54-03-924	mproc.processormanager	warning	"Executable processor file did not return output for spec: /opt/mountainlab/packages/system/rbdownload/rbdownload.mp"
  |ms3.bandpass_filter|            RUNNING ms3.bandpass_filter: /opt/mountainlab/packages/ms3/ms3.mp ms3.bandpass_filter --timeseries=/storage/mountainsort_examples/examples/example1_mlp/data/raw.mda --timeseries_out=/tmp/mountainlab/prvbucket/_mountainprocess/output_timeseries_out_96b15ee325 --freq_max=6000 --freq_min=300 --freq_wid=1000 --quantization_unit=0 --samplerate=30000 --subsample_factor=1 --_tempdir=/tmp/mountainlab/tmp_short_term/tempdir_WJM7M3H6XC 
  |ms3.bandpass_filter|            Expected peak RAM usage (MB): 1024
  |ms3.bandpass_filter|            samplerate/freq_min/freq_max/freq_wid: 30000 300 6000 1000
  |ms3.bandpass_filter|            ************+++ Using chunk size / overlap size: 252827 / 60000 (num threads=12)
  |ms3.bandpass_filter|            2275443/18000000 (12%) -- using 12 threads.
  |ms3.bandpass_filter|            12135696/18000000 (67%) -- using 12 threads.
  |ms3.bandpass_filter|            18000000/18000000 (100%) -- using 12 threads.
  |ms3.bandpass_filter|            Process completed successfully: ms3.bandpass_filter (Elapsed: 10.872 sec)
  |ms3.bandpass_filter|            making prv file: /tmp/mountainlab/prvbucket/_mountainprocess/output_console_out_96b15ee325.prv
  |ms3.bandpass_filter|            making prv file: /tmp/mountainlab/prvbucket/_mountainprocess/output_timeseries_out_96b15ee325.prv
----------------------------------------------------------------------------
Queueing job: ms3.whiten
  INPUTS: timeseries=[object Object]  
  PARAMS: quantization_unit=0  
----------------------------------------------------------------------------
  |ms3.whiten|                     2018-02-08:10-54-21-417	mproc.processormanager	warning	"Potential problem with executable processor file: /opt/mountainlab/packages/system/rbdownload/rbdownload.mp. Expected json output but got empty string."
  |ms3.whiten|                     2018-02-08:10-54-21-418	mproc.processormanager	warning	"Executable processor file did not return output for spec: /opt/mountainlab/packages/system/rbdownload/rbdownload.mp"
  |ms3.whiten|                     2018-02-08:10-54-21-566	mproc.processormanager	warning	"Potential problem with executable processor file: /opt/mountainlab/packages/system/rbdownload/rbdownload.mp. Expected json output but got empty string."
  |ms3.whiten|                     2018-02-08:10-54-21-566	mproc.processormanager	warning	"Executable processor file did not return output for spec: /opt/mountainlab/packages/system/rbdownload/rbdownload.mp"
  |ms3.whiten|                     RUNNING ms3.whiten: /opt/mountainlab/packages/ms3/ms3.mp ms3.whiten --timeseries=/tmp/mountainlab/prvbucket/_mountainprocess/output_timeseries_out_96b15ee325 --timeseries_out=/tmp/mountainlab/prvbucket/_mountainprocess/output_timeseries_out_81c3a2392c --quantization_unit=0 --_tempdir=/tmp/mountainlab/tmp_short_term/tempdir_O2PKK9EIFK 
  |ms3.whiten|                     Expected peak RAM (MB): 11.4441
  |ms3.whiten|                     Problem writing chunk in whiten
  |ms3.whiten|                     Problem writing chunk in whiten
  |ms3.whiten|                     Problem writing chunk in whiten
  |ms3.whiten|                     Problem writing chunk in whiten
  |ms3.whiten|                     Problem writing chunk in whiten
  |ms3.whiten|                     Problem writing chunk in whiten
  |ms3.whiten|                     Problem writing chunk in whiten
  |ms3.whiten|                     Problem writing chunk in whiten
  |ms3.whiten|                     Problem writing chunk in whiten
  |ms3.whiten|                     Problem writing chunk in whiten
  |ms3.whiten|                     Problem writing chunk in whiten
  |ms3.whiten|                     Problem writing chunk in whiten
  |ms3.whiten|                     Problem writing chunk in whiten
  |ms3.whiten|                     Problem writing chunk in whiten
  |ms3.whiten|                     Problem writing chunk in whiten
  |ms3.whiten|                     Problem writing chunk in whiten
  |ms3.whiten|                     Problem writing chunk in whiten
  |ms3.whiten|                     Problem writing chunk in whiten
  |ms3.whiten|                     Problem writing chunk in whiten
  |ms3.whiten|                     Problem writing chunk in whiten
  |ms3.whiten|                     Problem writing chunk in whiten
  |ms3.whiten|                     Problem writing chunk in whiten
  |ms3.whiten|                     Problem writing chunk in whiten
  |ms3.whiten|                     Problem writing chunk in whiten
  |ms3.whiten|                     Problem writing chunk in whiten
  |ms3.whiten|                     Problem writing chunk in whiten
  |ms3.whiten|                     Problem writing chunk in whiten
  |ms3.whiten|                     Problem writing chunk in whiten
  |ms3.whiten|                     Problem writing chunk in whiten
  |ms3.whiten|                     Problem writing chunk in whiten
  |ms3.whiten|                     Problem writing chunk in whiten
  |ms3.whiten|                     Problem writing chunk in whiten
  |ms3.whiten|                     Problem writing chunk in whiten
  |ms3.whiten|                     Problem writing chunk in whiten
  |ms3.whiten|                     Problem writing chunk in whiten
  |ms3.whiten|                     Problem writing chunk in whiten
  |ms3.whiten|                     Problem writing chunk in whiten
  |ms3.whiten|                     Problem writing chunk in whiten
  |ms3.whiten|                     Problem writing chunk in whiten
  |ms3.whiten|                     Problem writing chunk in whiten
  |ms3.whiten|                     Problem writing chunk in whiten
  |ms3.whiten|                     Problem writing chunk in whiten
  |ms3.whiten|                     Problem writing chunk in whiten
  |ms3.whiten|                     Problem writing chunk in whiten
  |ms3.whiten|                     Problem writing chunk in whiten
  |ms3.whiten|                     18000000/18000000 (100%)
  |ms3.whiten|                     18000000/18000000 (100%)
  |ms3.whiten|                     Process completed successfully: ms3.whiten (Elapsed: 1.987 sec)
  |ms3.whiten|                     Warning: Problem in TextFile::write. The contents of the file do not match what was expected. "/tmp/mountainlab/tmp_short_term/process_output_ms3.whiten_9I5RYFK9RT.json.tf.PRF7VE.tmp" 0 1110
  |ms3.whiten|                     Warning: Problem in TextFile::write. The contents of the file do not match what was expected. "/tmp/mountainlab/tmp_short_term/process_output_ms3.whiten_9I5RYFK9RT.json.tf.1R8ME9.tmp" 0 1110
  |ms3.whiten|                     Warning: Problem in TextFile -- unable to write file:  "/tmp/mountainlab/tmp_short_term/process_output_ms3.whiten_9I5RYFK9RT.json"
  |ms3.whiten|                     making prv file: /tmp/mountainlab/prvbucket/_mountainprocess/output_console_out_81c3a2392c.prv
  |ms3.whiten|                     making prv file: /tmp/mountainlab/prvbucket/_mountainprocess/output_timeseries_out_81c3a2392c.prv
Response file does not exist: /tmp/mountainlab/prvbucket/tmp.v0zs78gflT.json
Response file does not exist: /tmp/mountainlab/prvbucket/tmp.v0zs78gflT.json
Error in job (processor: ms3.whiten): Response file does not exist: /tmp/mountainlab/prvbucket/tmp.v0zs78gflT.json
Could not find input in running or pending jobs: pre_out
Error: Error in job (processor: ms3.whiten): Response file does not exist: /tmp/mountainlab/prvbucket/tmp.v0zs78gflT.json
Error: Error in job (processor: ms3.whiten): Response file does not exist: /tmp/mountainlab/prvbucket/tmp.v0zs78gflT.json
Stopped
Stopped
```

Appreciate the help!

**Comment by magland** [comment]
For the last issue, I think you are running out of space on /tmp again. For the other issues, those will be resolved in the next release.

In general we recommend using mlconfig tool to set the temporary directory.
