### ISSUE TITLE
Unexpected token in JSON

### ISSUE THREAD

**Issue by tbenst** [flatironinstitute/mountainsort#33]
I am able to run `mountainsort_examples/examples/example1_mlp/mountainsort3.mlp` just fine, including on my own data. However, I cannot run either `mountainlab/packages/mountainsortalg/mountainsortalg.mp` or `mountainlab/packages/ms3/ms3.mp` as I get the following error:

```
$ mlp-run /opt/mountainlab/packages/ms3/ms3.mp sort --raw=2018-01-23T15-04-19_raw.mda --firings_out=2018-01-23T15-04-19_firings.mda --samplerate=20000
Using pipeline: /opt/mountainlab/packages/ms3/ms3.mp
undefined:1
ELF
^

SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/usr/share/mlpipeline/utils/mlp/mlp-run:49:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
`

**Comment by magland** [comment]
The .mp is a binary executable, not a pipeline. It does not have a .mlp extension.

**Comment by tbenst** [comment]
ah, missed that!  would be good to update https://mountainsort.readthedocs.io/en/latest/first_sort.html `The mountainsort3 pipeline is found in ‘mountainlab/packages/mountainsort/pipelines’` to `mountainsort/pipelines/`

**Comment by magland** [comment]
Will update. Thanks!
