### ISSUE TITLE
ModuleNotFoundError: No module named 'basic_cpp'

### ISSUE THREAD

**Issue by maxhodak** [flatironinstitute/mountainsort#40]
Following the install instructions on https://mountainsort.readthedocs.io/en/latest/ and using the Ubuntu PPA, I get the following messages when running `mp-list-processors`:

```
max@retina:~/src/rSW$ mp-list-processors
2018-03-17:15-07-39-732	mproc.processormanager	warning	"Potential problem with executable processor file: /opt/mountainlab/packages/pyms/basic/basic.mp. Expected json output but got empty string."
2018-03-17:15-07-39-733	mproc.processormanager	warning	"Executable processor file did not return output for spec: /opt/mountainlab/packages/pyms/basic/basic.mp"
2018-03-17:15-07-40-080	mproc.processormanager	warning	"Potential problem with executable processor file: /opt/mountainlab/packages/pyms/curation/curation.mp. Expected json output but got empty string."
2018-03-17:15-07-40-080	mproc.processormanager	warning	"Executable processor file did not return output for spec: /opt/mountainlab/packages/pyms/curation/curation.mp"
2018-03-17:15-07-41-061	mproc.processormanager	warning	"Potential problem with executable processor file: /opt/mountainlab/packages/pyms/basic/basic.mp. Expected json output but got empty string."
2018-03-17:15-07-41-061	mproc.processormanager	warning	"Executable processor file did not return output for spec: /opt/mountainlab/packages/pyms/basic/basic.mp"
2018-03-17:15-07-41-360	mproc.processormanager	warning	"Potential problem with executable processor file: /opt/mountainlab/packages/pyms/curation/curation.mp. Expected json output but got empty string."
2018-03-17:15-07-41-360	mproc.processormanager	warning	"Executable processor file did not return output for spec: /opt/mountainlab/packages/pyms/curation/curation.mp"
```

Running one of the "executable processor files" listed produces the following output:
```
max@retina:~/src/rSW$ /opt/mountainlab/packages/pyms/basic/basic.mp
Traceback (most recent call last):
  File "/opt/mountainlab/packages/pyms/basic/basic.py", line 10, in <module>
    import p_extract_clips
  File "/opt/mountainlab/packages/pyms/basic/p_extract_clips.py", line 18, in <module>
    import basic_cpp as cpp
ModuleNotFoundError: No module named 'basic_cpp'
```

Despite this, if I forge ahead, MountainSort *appears* to run and work, but I can't really be confident. `mlpipeline` always seems to be empty (it renders a UI but the UI doesn't contain any high-information-content items) but `mountainview` appears to render spikes and do things when I click buttons.

I'm running Ubuntu 17.10.

**Comment by magland** [comment]
The Ubuntu ppa is for 16.04, so there is probably a missing python dependency. Would you be able to try the advanced installation, i.e., via compilation.

The alternative is to add the missing dependency by following *some* subset of the compilation/advanced installation instructions on the docs. That is to say, it may not be necessary to compile the C++ part.

**Comment by wysota** [comment]
PPA has been updated to include packages for 17.10. You might want to try them.
