### ISSUE TITLE
Sorting error - SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by vncntprvst** [flatironinstitute/mountainsort#44]
Hi,
MountainSort works fine on the synthetic data, but I get this error when trying to sort my own data. 
This seems like a simple error. 
Thanks. 

`mlp-run mountainsort3.mlp sort --raw=raw.mda --geom=geom.csv --firings_out=firings2.mda --_params=params.json --curate=true
undefined:1
{
^

SyntaxError: Unexpected token ﻿
    at Object.parse (native)
    at Object.<anonymous> (/usr/share/mlpipeline/utils/mlp/mlp-run:33:14)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
`

**Comment by magland** [comment]
Perhaps there is a problem with your params.json file. Could you attach that file, please?

**Comment by vncntprvst** [comment]
The .json format is not supported as attachment. Here's the params.json content: 
```
﻿{
  "samplerate":30000,
  "detect_sign":0,
  "adjacency_radius":0
}
```

**Comment by magland** [comment]
It looks fine. Sometimes there are weird invisible characters in text files. Could you try running it without the --_params flag? If that works (i.e., runs) then try to create a completely new .json file and type the text in.
J
